import {
  getAllPosts,
  getAllTags,
  getNumberOfPages,
  getPostByPage,
  getPostForTopPage,
} from "@/lib/notionAPI";
import SinglePost from "../../../components/Post/SinglePost";
import Head from "next/head";
import { GetStaticPaths, GetStaticProps } from "next";
import Pagination from "@/components/Pagination/Pagination";
import Tag from "@/components/Tag/Tag";

export const getStaticPaths: GetStaticPaths = async () => {
  const numberOfPage = await getNumberOfPages();

  let params = [];
  for (let i = 1; i <= numberOfPage; i++) {
    params.push({ params: { page: i.toString() } });
  }

  return {
    paths: params,
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const currentPage = context.params?.page;

  const postsByPage = await getPostByPage(parseInt(currentPage.toString(), 10));

  const numberOfPage = await getNumberOfPages();

  const allTags = await getAllTags()

  return {
    props: {
      postsByPage,
      numberOfPage,
      allTags
    },
    revalidate: 60,
  };
};

const BlogPageList = ({ postsByPage, numberOfPage, allTags }) => {
  return (
    <>
      <Head>
        <title>Notion Blog</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container w-full h-full mx-auto font-mono'>
        <h1 className='text-5xl font-medium text-center mb-16'>
          Notion Blog🚀
        </h1>
        <section className='sm:grid grid-cols-2 w-5/6 gap-3 mx-auto'>
          {postsByPage.map((post, id: number) => (
            <div key={id}>
              <SinglePost
                title={post.title}
                date={post.date}
                tags={post.tag}
                slug={post.slug}
                isPaginationPage={true}
              />
            </div>
          ))}
        </section>
        <Pagination numberOfPage={numberOfPage} tag={""} />
        <Tag tags={allTags} />
      </main>
    </>
  );
};

export default BlogPageList;
