import { getAllPosts } from "@/lib/notionAPI";
import SinglePost from "../components/Post/SinglePost";
import Head from "next/head";

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      allPosts,
    },
    revalidate: 60,
  };
};

export default function Home({ allPosts }) {
  console.log(allPosts);
  return (
    <>
      <Head>
        <title>Notion Blog</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container w-full h-full mx-auto font-mono'>
        <h1 className='text-5xl font-medium text-center mb-16'>
          Notion Blog🚀
        </h1>
        {allPosts.map((post, id) => (
          <div key={id} className='mx-4'>
            <SinglePost
              title={post.title}
              date={post.date}
              tags={post.tag}
              slug={post.slug}
            />
          </div>
        ))}
      </main>
    </>
  );
}
